### PR TITLE
MGMT-15850: Add a utility to remove duplicated documents from elasticsearch indices

### PR DESCRIPTION
**Pull request by danmanor**
Add a utility to remove duplicated documents from `elasticsearch` indices based on a comparison field.

### CODE REVIEW

**Comment by osherdp** [comment]
Let's add it to some existing repository rather than creating a repo for one script

**Comment by adriengentil** [comment]
@rccrdpccl do you foresee a usage of this script in other indices than the ones managed by prow-job-scraper?
If no, I think we can just put it in prow-jobs-scraper.

**Comment by rccrdpccl** [comment]
No, I don't think this would be used in other indices that we currently host in opensearch anytime soon

**Pull request closed without merging**
